---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prediction-generator
  namespace: rwml
data:
  MLFLOW_TRACKING_URI: "http://user:6440921D-2493-42AA-BE40-428CD753D81D@mlflow-tracking.mlflow.svc.cluster.local:80"
  RISINGWAVE_HOST: "risingwave.risingwave.svc.cluster.local"
  RISINGWAVE_PORT: "4567"
  RISINGWAVE_USER: "root"
  RISINGWAVE_PASSWORD: ""
  RISINGWAVE_DATABASE: "dev"
  RISINGWAVE_SCHEMA: "public"
  RISINGWAVE_INPUT_TABLE: "technical_indicators"
  RISINGWAVE_OUTPUT_TABLE: "predictions"
  PAIR: 'ETH/EUR'
  CANDLE_SECONDS: "60"
  PREDICTION_HORIZON_SECONDS: "300"
  MODEL_VERSION: "latest"