apiVersion: v1
kind: Service
metadata:
  name: prediction-api
  namespace: rwml
spec:
  selector:
    # app.kubernetes.io/name: prediction-api
    app: prediction-api
    # app.kubernetes.io/instance: prediction-api
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 8080 #The container port put in the cm