apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  namespace: strimzi
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
      - name: trades
        image: ghcr.io/karimabousselham/trades:0.1.2-beta.12345
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-c6c8-kafka-bootstrap.strimzi.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: "trades"