#
# https://kubernetes.io/docs/concepts/workloads/controllers/job/
#
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: training-pipeline-aed2
  namespace: rwml
spec:
  schedule: "0 * * * *" # Trigger the training every hour
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: training-pipeline
            image: training-pipeline:dev
            imagePullPolicy: Never # Use the local image
            env:
            #
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: MLFLOW_TRACKING_URI
            #
            - name: RISINGWAVE_HOST
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: RISINGWAVE_HOST
            #
            - name: RISINGWAVE_PORT
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: RISINGWAVE_PORT
            #
            - name: RISINGWAVE_USER
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: RISINGWAVE_USER
            - name: RISINGWAVE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: RISINGWAVE_PASSWORD
            - name: RISINGWAVE_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: RISINGWAVE_DATABASE
            - name: RISINGWAVE_TABLE
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: RISINGWAVE_TABLE
            - name: PAIR
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: PAIR
            - name: LOOKBACK_PERIOD
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: LOOKBACK_PERIOD
            - name: CANDLE_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: CANDLE_SECONDS
            - name: PREDICTION_HORIZON_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: PREDICTION_HORIZON_SECONDS
            - name: TRAIN_TEST_SPLIT
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: TRAIN_TEST_SPLIT
            - name: MAX_PERCENTAGE_ROWS_WITH_NULLS
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: MAX_PERCENTAGE_ROWS_WITH_NULLS
            - name: MAX_PERCENTAGE_DIFF_VS_BASELINE
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: MAX_PERCENTAGE_DIFF_VS_BASELINE
            - name: N_ROWS_FOR_DATA_PROFILING
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: N_ROWS_FOR_DATA_PROFILING
            - name: EDA_REPORT_HTML_PATH
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: EDA_REPORT_HTML_PATH
            - name: HYPERPARAM_SEARCH_N_SPLITS
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: HYPERPARAM_SEARCH_N_SPLITS
            - name: HYPERPARAM_SEARCH_TRIALS
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: HYPERPARAM_SEARCH_TRIALS
            - name: MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: MODEL_NAME
            - name: N_MODEL_CANDIDATES
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: N_MODEL_CANDIDATES
            - name: FEATURES
              valueFrom:
                configMapKeyRef:
                  name: training-pipeline
                  key: FEATURES
