#
#  https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/
#
#  kustomize build deployments/dev/news | kubectl apply -f -
#
---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rwml
resources:
  - ./news-d.yaml
# We decided to use a configmap generator instead of a configmap because there are sensitive 
# data like Crypotpanic API key which cannot be shared in a simple configmap and pushed
# to github repo
configMapGenerator:
  - name: news-config
    envs:
      - .env.kind 