apiVersion: v1
kind: Service
metadata:
  name: ml-stability
  namespace: rwml
spec:
  selector:
    # app.kubernetes.io/name: ml-stability
    app: ml-stability
    # app.kubernetes.io/instance: ml-stability
  ports:
    - protocol: TCP
      port: 11000 # The port exposed by the service
      targetPort: 11000 #The container port put in the cm